### ISSUE TITLE
Documentar todo passo a passo da criação desse projeto de boas práticas

### ISSUE THREAD

**Issue by devjoaomalta** [devjoaomalta/Projeto-gerencia#2]
# Documentar todo passo a passo da criação do projeto
---
### A corrigir:

- [x] Criar o README.md
- [x] Criar o commit.md e o pull_requests.md
- [ ] Documentar o passo a passo do que foi executado
---
